# Settings.yml
---
conf.py:
  ##==========================================
  ## define configuration data for conf.py as
  ## "parameter: value" pairs here:
  ##------------------------------------------
  todo_include_todos: True
  copyright: 2013 to now
  project: Collection of Incoming Notes
  version: 0.1
  release: 0.1.0
...
